[project]
name = "elscione-scraper"
version = "0.1.0"
dependencies = [
    "requests>=2.32",
    "beautifulsoup4>=4.12",
    "questionary>=2.0",
    "tqdm>=4.66",
    "playwright>=1.55.0",
    "redis>=5.0.0",
    "python-dotenv>=1.1.1",
    "pyfiglet>=1.0.2",
]

[project.scripts]
scrape = "main:cli"
